version: "3.9"
services:
  gate_g1:
    build: .
    container_name: gate_g1
    environment:
      - GATE_ID=G1
      - CLOUD_API=http://192.168.42.1:8010     # IP máy thật (Windows)
      - REDIS_URL=redis://192.168.42.1:6379/0  # Redis của Cloud
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data  
